# Data Structure Templating and Preliminary Cleaning Plans

In [21]:
import numpy as np
import pandas as pd

In [22]:
# Import Data
df = pd.read_csv('/home/tyler/Documents/Hard Drive Project Data/data_Q1_2019/drive_stats_2019_Q1/2019-01-01.csv')
print(df.shape)
df.head()

(106918, 129)

,date,serial_number,model,capacity_bytes,failure,smart_1_normalized,smart_1_raw,smart_2_normalized,smart_2_raw,smart_3_normalized,...,smart_250_normalized,smart_250_raw,smart_251_normalized,smart_251_raw,smart_252_normalized,smart_252_raw,smart_254_normalized,smart_254_raw,smart_255_normalized,smart_255_raw
0,2019-01-01,Z305B2QN,ST4000DM000,4000787030016,0,111,35673128,NaN,NaN,91.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-01-01,ZJV0XJQ4,ST12000NM0007,12000138625024,0,83,187116872,NaN,NaN,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019-01-01,ZJV0XJQ3,ST12000NM0007,12000138625024,0,73,19599104,NaN,NaN,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-01-01,ZJV0XJQ0,ST12000NM0007,12000138625024,0,81,136943696,NaN,NaN,93.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-01-01,PL1331LAHG1S4H,HGST HMS5C4040ALE640,4000787030016,0,100,0,134.0,103.0,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
# Use regular expression to drop columns with _raw data
df_norm = df[df.columns.drop(list(df.filter(regex='raw')))]
print(df_norm.shape)
df_norm.head()

(106918, 67)

,date,serial_number,model,capacity_bytes,failure,smart_1_normalized,smart_2_normalized,smart_3_normalized,smart_4_normalized,smart_5_normalized,...,smart_233_normalized,smart_235_normalized,smart_240_normalized,smart_241_normalized,smart_242_normalized,smart_250_normalized,smart_251_normalized,smart_252_normalized,smart_254_normalized,smart_255_normalized
0,2019-01-01,Z305B2QN,ST4000DM000,4000787030016,0,111,NaN,91.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
1,2019-01-01,ZJV0XJQ4,ST12000NM0007,12000138625024,0,83,NaN,98.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
2,2019-01-01,ZJV0XJQ3,ST12000NM0007,12000138625024,0,73,NaN,99.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
3,2019-01-01,ZJV0XJQ0,ST12000NM0007,12000138625024,0,81,NaN,93.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
4,2019-01-01,PL1331LAHG1S4H,HGST HMS5C4040ALE640,4000787030016,0,100,134.0,100.0,100.0,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
# Save list of indexes of observations known to be SSDs
df_smart173 = df[df['smart_173_normalized'] == 100.0]
index_drop = df_smart173.index.values.tolist()
index_drop

[15650,
 15671,
 33043,
 35550,
 35579,
 55517,
 55533,
 59895,
 59935,
 59964,
 67312,
 94442,
 99053,
 99336]

In [25]:
# Use index list to drop observations
df_hdd= df_norm.drop(index=index_drop)
df_nhdd = df_hdd.copy()

In [26]:
# Verify no entries remain that satisfy condition of having SSD metrics
df_smart173 = df_hdd[df_hdd['smart_173_normalized'] == 100.0]
df_smart173

Empty DataFrame
Columns: [date, serial_number, model, capacity_bytes, failure, smart_1_normalized, smart_2_normalized, smart_3_normalized, smart_4_normalized, smart_5_normalized, smart_7_normalized, smart_8_normalized, smart_9_normalized, smart_10_normalized, smart_11_normalized, smart_12_normalized, smart_13_normalized, smart_15_normalized, smart_16_normalized, smart_17_normalized, smart_22_normalized, smart_23_normalized, smart_24_normalized, smart_168_normalized, smart_170_normalized, smart_173_normalized, smart_174_normalized, smart_177_normalized, smart_179_normalized, smart_181_normalized, smart_182_normalized, smart_183_normalized, smart_184_normalized, smart_187_normalized, smart_188_normalized, smart_189_normalized, smart_190_normalized, smart_191_normalized, smart_192_normalized, smart_193_normalized, smart_194_normalized, smart_195_normalized, smart_196_normalized, smart_197_normalized, smart_198_normalized, smart_199_normalized, smart_200_normalized, smart_201_normalized, smart_218_normalized, smart_220_normalized, smart_222_normalized, smart_223_normalized, smart_224_normalized, smart_225_normalized, smart_226_normalized, smart_231_normalized, smart_232_normalized, smart_233_normalized, smart_235_normalized, smart_240_normalized, smart_241_normalized, smart_242_normalized, smart_250_normalized, smart_251_normalized, smart_252_normalized, smart_254_normalized, smart_255_normalized]
Index: []

[0 rows x 67 columns]

In [27]:
for column in df_hdd:
    vc = df_hdd[column].value_counts(dropna=False)
    col = column
    print(col)
    print(vc)
    print('\n')
    print('\n')

date
2019-01-01    106904
Name: date, dtype: int64




serial_number
ZJV2EMW6    1
ZA14AWCE    1
ZCH0655S    1
ZJV11B0Z    1
ZA143CXC    1
           ..
Z305D69P    1
ZA108Q4D    1
ZCH07Z6M    1
ZA143SQY    1
ZCH07Y3N    1
Name: serial_number, Length: 106904, dtype: int64




model
ST12000NM0007              31147
ST4000DM000                23236
HGST HMS5C4040BLE640       14550
ST8000NM0055               14383
ST8000DM002                 9874
HGST HMS5C4040ALE640        4678
ST6000DX000                 1524
HGST HUH721212ALN604        1278
ST10000NM0086               1210
TOSHIBA MG07ACA14TA         1204
HGST HUH728080ALE600        1045
ST500LM012 HN                604
TOSHIBA MQ01ABF050           528
WDC WD60EFRX                 382
TOSHIBA MQ01ABF050M          354
WDC WD5000LPVX               272
TOSHIBA MD04ABA400V          145
ST500LM030                   111
ST4000DM005                   58
WDC WD5000LPCX                56
HGST HDS5C4040ALE630          50
TOSHIBA MD04ABA500V           45
HGST HUS726040ALE610          28
ST8000DM005                   25
TOSHIBA HDWF180               20
WDC WD1600AAJS                19
Hitachi HDS5C4040ALE630       14
ST6000DM001                   13
WDC WD5000BPKT                11
TOSHIBA HDWE160               10
HGST HUH721010ALE600          10
ST8000DM004                    4
ST3160316AS                    3
WDC WD40EFRX                   2
ST6000DM004                    2
ST320LT007                     1
Hitachi HDS724040ALE640        1
ST1000LM024 HN                 1
ST3160318AS                    1
WDC WD2500AAJS                 1
ST250LM004 HN                  1
WDC WD3200AAJS                 1
WDC WD3200BEKX                 1
HGST HMS5C4040BLE641           1
Name: model, dtype: int64




capacity_bytes
4000787030016     42763
12000138625024    32425
8001563222016     25351
500107862016       1936
6001175126016      1931
10000831348736     1220
14000519643136     1204
5000981078016        45
160041885696         23
320072933376          3
250059350016          2
1000204886016         1
Name: capacity_bytes, dtype: int64




failure
0    106900
1         4
Name: failure, dtype: int64




smart_1_normalized
100    25228
83     11719
82      8429
81      6596
117     5224
80      5199
84      4588
79      4205
118     3382
119     3360
78      3331
77      2566
114     2471
76      2014
115     1689
116     1680
75      1602
74      1358
111     1253
120     1151
73      1043
113      895
72       867
112      863
200      745
71       630
108      613
70       550
69       452
110      444
109      437
68       341
105      332
67       278
107      224
106      222
66       220
65       187
102      160
104       98
103       94
64        73
101       46
99        24
98         5
95         3
97         3
92         2
96         2
86         1
91         1
93         1
94         1
54         1
57         1
Name: smart_1_normalized, dtype: int64




smart_2_normalized
NaN      82337
134.0    10757
133.0     6007
100.0     3425
135.0     2536
132.0      909
252.0      606
131.0      109
136.0       85
130.0       72
129.0       28
137.0        8
128.0        6
146.0        4
147.0        4
138.0        3
126.0        2
127.0        2
86.0         1
124.0        1
92.0         1
125.0        1
Name: smart_2_normalized, dtype: int64




smart_3_normalized
100.0    19598
92.0     11675
96.0     10037
98.0      9477
99.0      9088
         ...
208.0        1
118.0        1
223.0        1
171.0        1
168.0        1
Name: smart_3_normalized, Length: 111, dtype: int64




smart_4_normalized
100.0    106833
99.0         47
98.0          9
97.0          5
96.0          3
93.0          2
95.0          1
94.0          1
92.0          1
75.0          1
76.0          1
Name: smart_4_normalized, dtype: int64




smart_5_normalized
100.0    105481
200.0       744
252.0       606
99.0         24
98.0         13
97.0          7
96.0          6
94.0          4
95.0          3
74.0          2
88.0          2
58.0          1
92.0          1
59.0          1
85.0          1
91.0          1
199.0         1
31.0          1
82.0          1
61.0          1
93.0          1
86.0          1
78.0          1
Name: smart_5_normalized, dtype: int64




smart_7_normalized
100.0    24252
89.0      8322
95.0      7570
84.0      6437
96.0      5992
87.0      5928
86.0      5801
90.0      4952
88.0      4466
85.0      4340
94.0      4147
83.0      3523
81.0      3511
82.0      2370
77.0      2222
93.0      2159
80.0      1827
75.0      1425
92.0      1231
79.0      1048
63.0      1026
78.0       926
91.0       701
76.0       691
252.0      606
200.0      452
64.0       214
73.0       182
74.0       113
72.0       109
69.0        71
71.0        67
68.0        51
66.0        44
70.0        41
67.0        36
61.0        14
65.0        14
62.0        13
99.0         5
60.0         4
58.0         1
Name: smart_7_normalized, dtype: int64




smart_8_normalized
NaN      82337
113.0    15089
100.0     3424
111.0     2043
115.0     1493
128.0     1224
252.0      606
109.0      323
117.0      281
107.0       49
119.0       12
140.0        9
132.0        8
136.0        6
Name: smart_8_normalized, dtype: int64




smart_9_normalized
98     8944
100    6395
95     6016
89     5940
97     5427
       ...
23        1
28        1
20        1
25        1
35        1
Name: smart_9_normalized, Length: 81, dtype: int64




smart_10_normalized
100.0    106162
252.0       606
95.0        115
90.0         16
75.0          1
85.0          1
101.0         1
107.0         1
80.0          1
Name: smart_10_normalized, dtype: int64




smart_11_normalized
NaN      105553
100.0      1176
99.0        144
98.0         21
97.0          7
95.0          1
92.0          1
91.0          1
Name: smart_11_normalized, dtype: int64




smart_12_normalized
100    106903
99          1
Name: smart_12_normalized, dtype: int64




smart_13_normalized
NaN    106904
Name: smart_13_normalized, dtype: int64




smart_15_normalized
NaN    106904
Name: smart_15_normalized, dtype: int64




smart_16_normalized
NaN    106904
Name: smart_16_normalized, dtype: int64




smart_17_normalized
NaN    106904
Name: smart_17_normalized, dtype: int64




smart_22_normalized
NaN      104571
100.0      2332
81.0          1
Name: smart_22_normalized, dtype: int64




smart_23_normalized
NaN      105700
100.0      1204
Name: smart_23_normalized, dtype: int64




smart_24_normalized
NaN      105700
100.0      1202
96.0          1
99.0          1
Name: smart_24_normalized, dtype: int64




smart_168_normalized
NaN    106904
Name: smart_168_normalized, dtype: int64




smart_170_normalized
NaN    106904
Name: smart_170_normalized, dtype: int64




smart_173_normalized
NaN    106904
Name: smart_173_normalized, dtype: int64




smart_174_normalized
NaN    106904
Name: smart_174_normalized, dtype: int64




smart_177_normalized
NaN    106904
Name: smart_177_normalized, dtype: int64




smart_179_normalized
NaN    106904
Name: smart_179_normalized, dtype: int64




smart_181_normalized
NaN    106904
Name: smart_181_normalized, dtype: int64




smart_182_normalized
NaN    106904
Name: smart_182_normalized, dtype: int64




smart_183_normalized
NaN      82078
100.0    21239
98.0      1742
99.0       945
88.0       161
         ...
27.0         1
21.0         1
6.0          1
16.0         1
39.0         1
Name: smart_183_normalized, Length: 80, dtype: int64




smart_184_normalized
NaN      56459
100.0    50428
99.0         5
98.0         4
95.0         3
28.0         1
94.0         1
96.0         1
89.0         1
81.0         1
Name: smart_184_normalized, dtype: int64




smart_187_normalized
100.0    80722
NaN      25312
99.0       231
97.0       162
98.0       117
96.0        63
94.0        62
82.0        57
95.0        26
93.0        17
88.0        16
91.0        13
92.0        12
90.0        11
89.0         9
87.0         8
86.0         7
84.0         6
85.0         6
79.0         5
83.0         4
73.0         3
65.0         3
64.0         3
80.0         3
69.0         2
78.0         2
77.0         2
62.0         2
75.0         2
74.0         2
81.0         2
72.0         1
61.0         1
46.0         1
67.0         1
55.0         1
5.0          1
71.0         1
1.0          1
6.0          1
54.0         1
68.0         1
49.0         1
Name: smart_187_normalized, dtype: int64




smart_188_normalized
100.0    81592
NaN      25312
Name: smart_188_normalized, dtype: int64




smart_189_normalized
NaN      56459
100.0    46735
99.0       340
97.0       333
98.0       316
         ...
13.0         1
3.0          1
29.0         1
5.0          1
41.0         1
Name: smart_189_normalized, Length: 89, dtype: int64




smart_190_normalized
NaN     25312
72.0     4899
73.0     4899
79.0     4373
78.0     4285
74.0     4280
71.0     4251
77.0     4202
70.0     4066
69.0     4032
76.0     3990
75.0     3972
68.0     3840
67.0     3388
65.0     3225
66.0     3110
80.0     3105
64.0     2807
63.0     2328
81.0     2192
82.0     1784
62.0     1716
61.0     1379
60.0     1095
59.0      976
58.0      748
83.0      671
57.0      633
56.0      411
55.0      298
84.0      205
54.0      200
53.0      107
52.0       57
85.0       39
51.0       18
50.0       10
49.0        1
Name: smart_190_normalized, dtype: int64




smart_191_normalized
NaN      53407
100.0    27837
97.0      4379
98.0      3962
96.0      3062
         ...
10.0         5
15.0         5
13.0         4
9.0          3
5.0          2
Name: smart_191_normalized, Length: 102, dtype: int64




smart_192_normalized
100.0    104879
200.0       745
91.0        384
252.0       361
92.0        266
93.0        138
90.0         65
77.0         13
76.0         10
75.0          7
78.0          6
98.0          5
74.0          5
NaN           4
99.0          4
89.0          3
88.0          1
83.0          1
79.0          1
94.0          1
80.0          1
95.0          1
73.0          1
97.0          1
46.0          1
Name: smart_192_normalized, dtype: int64




smart_193_normalized
100.0    54444
98.0      5649
93.0      5042
99.0      4850
92.0      4219
         ...
161.0        1
198.0        1
144.0        1
146.0        1
179.0        1
Name: smart_193_normalized, Length: 150, dtype: int64

smart_194_normalized
28     4899
27     4899
21     4373
22     4285
26     4280
       ...
55        1
97        1
57        1
98        1
103       1
Name: smart_194_normalized, Length: 106, dtype: int64




smart_195_normalized
NaN     48111
1.0     11937
83.0     9270
82.0     6483
81.0     5084
        ...
59.0        1
58.0        1
85.0        1
99.0        1
88.0        1
Name: smart_195_normalized, Length: 83, dtype: int64




smart_196_normalized
NaN      81592
100.0    23947
200.0      745
252.0      606
96.0         3
77.0         1
82.0         1
74.0         1
70.0         1
69.0         1
34.0         1
12.0         1
83.0         1
40.0         1
98.0         1
97.0         1
Name: smart_196_normalized, dtype: int64




smart_197_normalized
100.0    105553
200.0       745
252.0       602
98.0          3
88.0          1
Name: smart_197_normalized, dtype: int64




smart_198_normalized
100.0    106275
252.0       606
200.0        19
98.0          3
88.0          1
Name: smart_198_normalized, dtype: int64




smart_199_normalized
200.0    106892
100.0        12
Name: smart_199_normalized, dtype: int64




smart_200_normalized
NaN      73196
100.0    33685
200.0       19
99.0         3
1.0          1
Name: smart_200_normalized, dtype: int64




smart_201_normalized
NaN    106904
Name: smart_201_normalized, dtype: int64




smart_218_normalized
NaN    106904
Name: smart_218_normalized, dtype: int64




smart_220_normalized
NaN      104598
100.0      2306
Name: smart_220_normalized, dtype: int64




smart_222_normalized
NaN     104598
95.0      1206
21.0        95
16.0        88
75.0        76
61.0        71
71.0        58
81.0        56
79.0        47
58.0        45
59.0        37
83.0        37
78.0        34
86.0        31
85.0        29
90.0        29
68.0        29
80.0        27
66.0        24
45.0        21
72.0        20
67.0        20
69.0        19
53.0        18
77.0        18
60.0        16
48.0        15
55.0        14
64.0        14
47.0        13
88.0        11
92.0        10
97.0         8
91.0         8
98.0         7
82.0         7
74.0         7
87.0         6
70.0         5
76.0         4
62.0         4
89.0         4
99.0         3
94.0         2
84.0         2
93.0         2
24.0         1
23.0         1
40.0         1
19.0         1
52.0         1
37.0         1
26.0         1
50.0         1
96.0         1
Name: smart_222_normalized, dtype: int64




smart_223_normalized
NaN      103992
100.0      2737
99.0        144
98.0         21
97.0          7
95.0          1
92.0          1
91.0          1
Name: smart_223_normalized, dtype: int64




smart_224_normalized
NaN      104598
100.0      2306
Name: smart_224_normalized, dtype: int64




smart_225_normalized
NaN     106298
1.0         66
93.0        43
92.0        34
85.0        33
         ...
36.0         1
31.0         1
7.0          1
45.0         1
35.0         1
Name: smart_225_normalized, Length: 88, dtype: int64




smart_226_normalized
NaN      104598
100.0      2306
Name: smart_226_normalized, dtype: int64




smart_231_normalized
NaN    106904
Name: smart_231_normalized, dtype: int64




smart_232_normalized
NaN    106904
Name: smart_232_normalized, dtype: int64




smart_233_normalized
NaN    106904
Name: smart_233_normalized, dtype: int64




smart_235_normalized
NaN    106904
Name: smart_235_normalized, dtype: int64




smart_240_normalized
100.0    83898
NaN      22927
66.0        16
70.0        11
58.0         6
48.0         6
68.0         4
47.0         3
61.0         3
37.0         3
60.0         3
32.0         2
33.0         2
63.0         2
46.0         2
79.0         1
71.0         1
50.0         1
41.0         1
36.0         1
45.0         1
62.0         1
81.0         1
51.0         1
40.0         1
38.0         1
59.0         1
72.0         1
65.0         1
77.0         1
49.0         1
Name: smart_240_normalized, dtype: int64




smart_241_normalized
100.0    81592
NaN      25301
200.0       11
Name: smart_241_normalized, dtype: int64




smart_242_normalized
100.0    81592
NaN      25301
200.0       11
Name: smart_242_normalized, dtype: int64




smart_250_normalized
NaN    106903
1.0         1
Name: smart_250_normalized, dtype: int64




smart_251_normalized
NaN    106903
1.0         1
Name: smart_251_normalized, dtype: int64




smart_252_normalized
NaN      106903
100.0         1
Name: smart_252_normalized, dtype: int64




smart_254_normalized
NaN      106781
100.0       112
200.0        11
Name: smart_254_normalized, dtype: int64




smart_255_normalized
NaN    106904
Name: smart_255_normalized, dtype: int64

In [29]:
df_hdd['failure'].value_counts(normalize=True)

0    0.999963
1    0.000037
Name: failure, dtype: float64

In [53]:
# Make previous operations a modular function
def data_clean(df):
    """Takes in a dataframe, removes raw values and any SSD devices, prints class baselines
    and returns a dataframe with only HDD."""
    df = df.copy()
    
    # Convert 'date' to datetime
    df['date'] = pd.to_datetime(df['date'], infer_datetime_format=True)
    # Use regular expression to drop columns with _raw data
    df_norm = df[df.columns.drop(list(df.filter(regex='raw')))]
    # Identify any SSDs, save indices to list
    df_smart173 = df_norm[df_norm['smart_173_normalized'] == 100.0]
    index_drop = df_smart173.index.values.tolist()
    # Remove observations from dataframe
    df_hdd= df_norm.drop(index=index_drop)

    # Print class baselines
    print('Raw and normalized counts for Failure class target')
    print(df_hdd['failure'].value_counts())
    print(df_hdd['failure'].value_counts(normalize=True))
    # Print Shape
    print("\nShape of the DataFrame:\n", df_hdd.shape)
    
    
    return df_hdd

In [31]:
# Import Concatenated Data
df_concat = pd.read_csv('/home/tyler/Documents/Data Subset/combined_csv.csv')
print(df_concat.shape)
df_concat.head()

(1074554, 129)

,date,serial_number,model,capacity_bytes,failure,smart_1_normalized,smart_1_raw,smart_2_normalized,smart_2_raw,smart_3_normalized,...,smart_250_normalized,smart_250_raw,smart_251_normalized,smart_251_raw,smart_252_normalized,smart_252_raw,smart_254_normalized,smart_254_raw,smart_255_normalized,smart_255_raw
0,2019-01-09,Z305B2QN,ST4000DM000,4000787030016,0,110.0,25853096.0,NaN,NaN,91.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-01-09,ZJV0XJQ4,ST12000NM0007,12000138625024,0,83.0,204969616.0,NaN,NaN,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019-01-09,ZJV0XJQ3,ST12000NM0007,12000138625024,0,84.0,242501136.0,NaN,NaN,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-01-09,ZJV0XJQ0,ST12000NM0007,12000138625024,0,74.0,24137328.0,NaN,NaN,93.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-01-09,PL1331LAHG1S4H,HGST HMS5C4040ALE640,4000787030016,0,100.0,0.0,134.0,103.0,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
df_concat = data_clean(df_concat)
df_concat.head()

Raw and normalized counts for Failure class target
0    1074329
1         51
Name: failure, dtype: int64
0    0.999953
1    0.000047
Name: failure, dtype: float64

Shape of the DataFrame:
 (1074380, 67)

,date,serial_number,model,capacity_bytes,failure,smart_1_normalized,smart_2_normalized,smart_3_normalized,smart_4_normalized,smart_5_normalized,...,smart_233_normalized,smart_235_normalized,smart_240_normalized,smart_241_normalized,smart_242_normalized,smart_250_normalized,smart_251_normalized,smart_252_normalized,smart_254_normalized,smart_255_normalized
0,2019-01-09,Z305B2QN,ST4000DM000,4000787030016,0,110.0,NaN,91.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
1,2019-01-09,ZJV0XJQ4,ST12000NM0007,12000138625024,0,83.0,NaN,98.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
2,2019-01-09,ZJV0XJQ3,ST12000NM0007,12000138625024,0,84.0,NaN,99.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
3,2019-01-09,ZJV0XJQ0,ST12000NM0007,12000138625024,0,74.0,NaN,93.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
4,2019-01-09,PL1331LAHG1S4H,HGST HMS5C4040ALE640,4000787030016,0,100.0,134.0,100.0,100.0,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
# Look at entries where failure = true
failed_drives = df_concat[df_concat['failure'] == 1]
failed_drives

,date,serial_number,model,capacity_bytes,failure,smart_1_normalized,smart_2_normalized,smart_3_normalized,smart_4_normalized,smart_5_normalized,...,smart_233_normalized,smart_235_normalized,smart_240_normalized,smart_241_normalized,smart_242_normalized,smart_250_normalized,smart_251_normalized,smart_252_normalized,smart_254_normalized,smart_255_normalized
39899,2019-01-09,ZA11X9WD,ST8000DM002,8001563222016,1,68.0,NaN,84.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
101930,2019-01-09,ZCH06TSA,ST12000NM0007,12000138625024,1,81.0,NaN,97.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
110725,2019-01-03,W300THEG,ST4000DM000,4000787030016,1,113.0,NaN,99.0,100.0,99.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
121711,2019-01-03,WCT0EJDY,ST8000DM004,8001563222016,1,55.0,NaN,99.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
133790,2019-01-03,ZCH0C6VX,ST12000NM0007,12000138625024,1,84.0,NaN,95.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
157596,2019-01-03,S2ZYJ9CG108681,ST500LM012 HN,500107862016,1,100.0,252.0,94.0,100.0,252.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
165380,2019-01-03,ZA11QHJ1,ST8000DM002,8001563222016,1,71.0,NaN,92.0,100.0,99.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
170392,2019-01-03,ZCH08BSC,ST12000NM0007,12000138625024,1,83.0,NaN,92.0,100.0,93.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
204800,2019-01-03,ZCH0931T,ST12000NM0007,12000138625024,1,82.0,NaN,96.0,100.0,92.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
220917,2019-01-02,ZDEB35E7,ST500LM030,500107862016,1,80.0,NaN,100.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,100.0,NaN
228343,2019-01-02,ZCH07RLC,ST12000NM0007,12000138625024,1,78.0,NaN,97.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
250281,2019-01-02,ZA120GQQ,ST8000DM002,8001563222016,1,55.0,NaN,93.0,100.0,99.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
289903,2019-01-02,Z302T6AB,ST4000DM000,4000787030016,1,114.0,NaN,96.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
294020,2019-01-02,Z3026Q5Y,ST4000DM000,4000787030016,1,110.0,NaN,92.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
328393,2019-01-07,S2ZYJ9FG404776,ST500LM012 HN,500107862016,1,100.0,252.0,95.0,100.0,252.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350264,2019-01-07,ZCH076TV,ST12000NM0007,12000138625024,1,82.0,NaN,96.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
362663,2019-01-07,ZCH07JDQ,ST12000NM0007,12000138625024,1,82.0,NaN,94.0,100.0,97.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
376017,2019-01-07,ZCH06ZQA,ST12000NM0007,12000138625024,1,84.0,NaN,97.0,100.0,98.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
383387,2019-01-07,ZJV0WEQM,ST12000NM0007,12000138625024,1,82.0,NaN,96.0,100.0,95.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
387611,2019-01-07,ZA13R3XX,ST8000DM002,8001563222016,1,58.0,NaN,96.0,100.0,99.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
408318,2019-01-07,188DT93WT,TOSHIBA MQ01ABF050M,500107862016,1,100.0,100.0,100.0,100.0,100.0,...,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429020,2019-01-07,ZJV0DH3Q,ST12000NM0007,12000138625024,1,83.0,NaN,91.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
436942,2019-01-10,Z304JMZP,ST4000DM000,4000787030016,1,114.0,NaN,92.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
438616,2019-01-10,87DFWOG3T,TOSHIBA MQ01ABF050,500107862016,1,100.0,100.0,100.0,100.0,100.0,...,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
457779,2019-01-10,ZA153S9S,ST8000NM0055,8001563222016,1,83.0,NaN,94.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
474748,2019-01-10,ZA180QHT,ST8000NM0055,8001563222016,1,71.0,NaN,98.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
481028,2019-01-10,ZCH06WP8,ST12000NM0007,12000138625024,1,71.0,NaN,90.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
486796,2019-01-10,ZJV00N9A,ST12000NM0007,12000138625024,1,82.0,NaN,94.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
507306,2019-01-10,ZCH08VPK,ST12000NM0007,12000138625024,1,83.0,NaN,94.0,100.0,88.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
520521,2019-01-10,Z304ZBFY,ST4000DM000,4000787030016,1,117.0,NaN,94.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
527545,2019-01-10,ZCH0BMML,ST12000NM0007,12000138625024,1,81.0,NaN,90.0,100.0,99.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
536534,2019-01-10,ZCH06MRJ,ST12000NM0007,12000138625024,1,75.0,NaN,96.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
561142,2019-01-06,ZA18CEVN,ST8000NM0055,8001563222016,1,68.0,NaN,98.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
629249,2019-01-06,ZCH07H2T,ST12000NM0007,12000138625024,1,82.0,NaN,96.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
673781,2019-01-04,ZA13R2NE,ST8000DM002,8001563222016,1,79.0,NaN,90.0,100.0,95.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
683650,2019-01-04,ZCH075WD,ST12000NM0007,12000138625024,1,80.0,NaN,97.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
738090,2019-01-04,ZA18145R,ST8000NM0055,8001563222016,1,82.0,NaN,92.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
753243,2019-01-08,PL2331LAH9R55J,HGST HMS5C4040BLE640,4000787030016,1,100.0,134.0,100.0,100.0,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
782337,2019-01-08,Z3040Z4M,ST4000DM000,4000787030016,1,119.0,NaN,95.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
789932,2019-01-08,ZCH0DVJN,ST12000NM0007,12000138625024,1,82.0,NaN,95.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
801327,2019-01-08,ZCH0B8ZF,ST12000NM0007,12000138625024,1,80.0,NaN,96.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
814317,2019-01-08,ZA13ZS5A,ST8000DM002,8001563222016,1,69.0,NaN,91.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
815665,2019-01-08,ZA180YYT,ST8000NM0055,8001563222016,1,83.0,NaN,98.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
820913,2019-01-08,ZCH09257,ST12000NM0007,12000138625024,1,83.0,NaN,96.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
914737,2019-01-05,ZJV0WCS2,ST12000NM0007,12000138625024,1,83.0,NaN,94.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
924369,2019-01-05,ZDEB1F1G,ST500LM030,500107862016,1,78.0,NaN,100.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,100.0,NaN
955488,2019-01-05,66GHS5MMS,TOSHIBA MQ01ABF050,500107862016,1,100.0,100.0,100.0,100.0,100.0,...,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
984957,2019-01-01,ZA18197Z,ST8000NM0055,8001563222016,1,57.0,NaN,92.0,100.0,93.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
1035521,2019-01-01,S300YTAY,ST4000DM000,4000787030016,1,117.0,NaN,92.0,100.0,99.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
1039173,2019-01-01,S300ZREZ,ST4000DM000,4000787030016,1,97.0,NaN,92.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN
1071441,2019-01-01,ZA180YM3,ST8000NM0055,8001563222016,1,77.0,NaN,92.0,100.0,100.0,...,NaN,NaN,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN

In [58]:
# Make sure there's no failure leakage
failed_drives['serial_number'].value_counts(ascending=False)

ZCH0C6VX          1
ZCH08BSC          1
ZJV0WEQM          1
ZCH075WD          1
ZCH07RLC          1
S300ZREZ          1
ZA11QHJ1          1
W300THEG          1
WCT0EJDY          1
ZA13ZS5A          1
ZDEB1F1G          1
Z302T6AB          1
S2ZYJ9CG108681    1
ZCH08VPK          1
ZCH06WP8          1
ZA18CEVN          1
Z304ZBFY          1
ZA13R3XX          1
PL2331LAH9R55J    1
ZCH0B8ZF          1
ZJV0DH3Q          1
ZCH07JDQ          1
87DFWOG3T         1
ZJV00N9A          1
ZCH06ZQA          1
ZCH09257          1
ZJV0WCS2          1
ZCH06TSA          1
ZA120GQQ          1
ZCH07H2T          1
ZA18197Z          1
ZA180YM3          1
S2ZYJ9FG404776    1
Z3040Z4M          1
ZA153S9S          1
66GHS5MMS         1
ZCH0BMML          1
ZA18145R          1
Z3026Q5Y          1
188DT93WT         1
ZCH0931T          1
ZA11X9WD          1
ZDEB35E7          1
ZA180QHT          1
ZCH076TV          1
ZA180YYT          1
S300YTAY          1
ZCH0DVJN          1
ZCH06MRJ          1
ZA13R2NE          1
Z304JMZP          1
Name: serial_number, dtype: int64